datafile = "/home/ahess/git/EigenfrequencyTransformation/continuous_spectrum_raw.npz"
filep = "/home/ahess/Downloads/New_TEline2022-ESR-204Pt-H-208Pb-nostripper_512.4MeV.lpp"
alphap = "0.512"
harmonics = "1"
refion = "207Pb78+"
circumference = "108.4"
highlight_ions = ""
mode = "Frequency"
value = "1930820"
sim_scalingfactor = ""
remove_baseline_checkbox = false
psd_baseline_removed_l = "1000000"
peak_threshold_pct = "0.05"
min_distance = "10"
matching_freq_min = ""
matching_freq_max = ""
correction = ""
nions = "100"
reload_data = false
simulation_result = ""
matched_result = ""
alphap_min = ""
alphap_max = ""
alphap_step = ""
fref_min = ""
fref_max = ""
threshold = "1000"
